name: Build
on: [push]
jobs:
  build:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SonarCloud scanner
        run: |
          dotnet tool update --global dotnet-sonarscanner

      - name: Install coverlet
        id: install-coverlet
        run: |
          dotnet tool install --global dotnet-coverage

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.2.0

      - name: Begin sonarscanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner begin /k:"Tr00d_CleanEventSourcing" /o:"tr00d-orga" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

      - name: Build
        id: build
        run: dotnet build --no-incremental

      - name: Test
        id: test
        run: dotnet-coverage collect 'dotnet test --no-build' -f xml  -o 'coverage.xml'

      - name: End sonarscanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"