name: Mutation Testing
on: workflow_dispatch
jobs:
  mutation:
    name: Run mutation testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Install Stryker
        id: install-stryker
        run: |
          dotnet tool install -g dotnet-stryker
          
      - name: Mutation
        id: mutation
        run: |
          cd tests/CleanEventSourcing.Api.Tests
          dotnet stryker

      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: tests/CleanEventSourcing.Api.Tests/StrykerOutput/**/reports/mutation-report.html
